name: Publish Native AOT Release

on:
  release:
    types: [published]

jobs:
  build-win:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET 9
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'

      - name: Publish AOT (Windows)
        run: dotnet publish ./Source/InbresTest.StartApp/InbresTest.StartApp.csproj -r win-x64 -c Release

      - name: Create ZIP (Windows)
        shell: powershell
        run: |
          $PUBLISH_DIR = "./Source/InbresTest.StartApp/bin/Release/net9.0/win-x64/publish"
          # Используем Compress-Archive, нативный инструмент Windows
          Compress-Archive -Path "$PUBLISH_DIR\*" -DestinationPath "InbresTest-win-x64.zip" -Force

      - name: Upload to Release
        uses: softprops/action-gh-release@v2
        with:
          files: InbresTest-win-x64.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  
